steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pictophone-be', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pictophone-be']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 
    'deploy', 
    'pictophone-be',
    '--project', '$_ENV_PROJECT',
    '--region', 'us-east1',
    '--image', 'gcr.io/$PROJECT_ID/pictophone-be', 
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--service-account', 'backend@$_ENV_PROJECT.iam.gserviceaccount.com'
  ]
images:
- gcr.io/$PROJECT_ID/pictophone-be