version: "3.9"  # optional since v1.27.0
services:
  grpc:
    image: gcr.io/pictophone-test/pictophone-be
    build: 
      context: .
      dockerfile: ./config/server/Dockerfile
    environment:
      - RUST_LOG=info,server=trace
    ports:
      - "8080:8080"
      - "9090:9090"