version: "3.9"  # optional since v1.27.0
services:
  server:
    image: gcr.io/pictophone-test/server
    build: 
      context: .
      dockerfile: ./config/server/Dockerfile
    environment:
      - RUST_LOG=info,server=trace
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - server-deps
  server-deps:
    image: gcr.io/pictophone-test/server-deps
    build: 
      context: .
      dockerfile: ./config/server-deps/Dockerfile
