/* tslint:disable */
// generated by typescript-json-validator
import Ajv from 'ajv';
import {BoringPlayerGame1_1, RespondToPromptPlayerGame1_1, FinishedPlayerGame1_1, ExportedPlayer1_1, ExportedSeries1_0, ExportedSeriesEntry1_0, ActionSubmission1_0, PlayerGame1_1} from './Export';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ActionSubmission1_0": {
      "else": {
        "else": {
          "properties": {
            "kind": {
              "enum": [
                "word",
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "if": {
          "properties": {
            "kind": {
              "enum": [
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "kind"
          ]
        },
        "then": {
          "defaultProperties": [
          ],
          "properties": {
            "drawingId": {
              "type": "string"
            },
            "kind": {
              "enum": [
                "drawing"
              ],
              "type": "string"
            }
          },
          "required": [
            "drawingId",
            "kind"
          ],
          "type": "object"
        }
      },
      "if": {
        "properties": {
          "kind": {
            "enum": [
              "word"
            ],
            "type": "string"
          }
        },
        "required": [
          "kind"
        ]
      },
      "then": {
        "defaultProperties": [
        ],
        "properties": {
          "kind": {
            "enum": [
              "word"
            ],
            "type": "string"
          },
          "word": {
            "maxLength": 1024,
            "minLength": 1,
            "type": "string"
          }
        },
        "required": [
          "kind",
          "word"
        ],
        "type": "object"
      }
    },
    "BoringPlayerGame1_1": {
      "defaultProperties": [
      ],
      "properties": {
        "players": {
          "items": {
            "$ref": "#/definitions/ExportedPlayer1_1"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "FIRST_PROMPT",
            "UNSTARTED",
            "WAITING_FOR_PROMPT"
          ],
          "type": "string"
        }
      },
      "required": [
        "players",
        "state"
      ],
      "type": "object"
    },
    "ExportedPlayer1_1": {
      "defaultProperties": [
      ],
      "properties": {
        "displayName": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "displayName",
        "id"
      ],
      "type": "object"
    },
    "ExportedSeries1_0": {
      "defaultProperties": [
      ],
      "properties": {
        "entries": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "playerId": {
                "type": "string"
              },
              "submission": {
                "anyOf": [
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "kind": {
                        "enum": [
                          "word"
                        ],
                        "type": "string"
                      },
                      "word": {
                        "maxLength": 1024,
                        "minLength": 1,
                        "type": "string"
                      }
                    },
                    "required": [
                      "kind",
                      "word"
                    ],
                    "type": "object"
                  },
                  {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "drawingId": {
                        "type": "string"
                      },
                      "kind": {
                        "enum": [
                          "drawing"
                        ],
                        "type": "string"
                      }
                    },
                    "required": [
                      "drawingId",
                      "kind"
                    ],
                    "type": "object"
                  }
                ]
              }
            },
            "required": [
              "playerId",
              "submission"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "entries"
      ],
      "type": "object"
    },
    "ExportedSeriesEntry1_0": {
      "defaultProperties": [
      ],
      "properties": {
        "playerId": {
          "type": "string"
        },
        "submission": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "word"
                  ],
                  "type": "string"
                },
                "word": {
                  "maxLength": 1024,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "word"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "drawingId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "drawing"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "drawingId",
                "kind"
              ],
              "type": "object"
            }
          ]
        }
      },
      "required": [
        "playerId",
        "submission"
      ],
      "type": "object"
    },
    "FinishedPlayerGame1_1": {
      "defaultProperties": [
      ],
      "properties": {
        "players": {
          "items": {
            "$ref": "#/definitions/ExportedPlayer1_1"
          },
          "type": "array"
        },
        "series": {
          "items": {
            "defaultProperties": [
            ],
            "properties": {
              "entries": {
                "items": {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "playerId": {
                      "type": "string"
                    },
                    "submission": {
                      "anyOf": [
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "kind": {
                              "enum": [
                                "word"
                              ],
                              "type": "string"
                            },
                            "word": {
                              "maxLength": 1024,
                              "minLength": 1,
                              "type": "string"
                            }
                          },
                          "required": [
                            "kind",
                            "word"
                          ],
                          "type": "object"
                        },
                        {
                          "defaultProperties": [
                          ],
                          "properties": {
                            "drawingId": {
                              "type": "string"
                            },
                            "kind": {
                              "enum": [
                                "drawing"
                              ],
                              "type": "string"
                            }
                          },
                          "required": [
                            "drawingId",
                            "kind"
                          ],
                          "type": "object"
                        }
                      ]
                    }
                  },
                  "required": [
                    "playerId",
                    "submission"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "required": [
              "entries"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "state": {
          "enum": [
            "GAME_OVER"
          ],
          "type": "string"
        }
      },
      "required": [
        "players",
        "series",
        "state"
      ],
      "type": "object"
    },
    "PlayerGame1_1": {
      "anyOf": [
        {
          "defaultProperties": [
          ],
          "properties": {
            "players": {
              "items": {
                "$ref": "#/definitions/ExportedPlayer1_1"
              },
              "type": "array"
            },
            "state": {
              "enum": [
                "FIRST_PROMPT",
                "UNSTARTED",
                "WAITING_FOR_PROMPT"
              ],
              "type": "string"
            }
          },
          "required": [
            "players",
            "state"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "players": {
              "items": {
                "$ref": "#/definitions/ExportedPlayer1_1"
              },
              "type": "array"
            },
            "prompt": {
              "anyOf": [
                {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "kind": {
                      "enum": [
                        "word"
                      ],
                      "type": "string"
                    },
                    "word": {
                      "maxLength": 1024,
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [
                    "kind",
                    "word"
                  ],
                  "type": "object"
                },
                {
                  "defaultProperties": [
                  ],
                  "properties": {
                    "drawingId": {
                      "type": "string"
                    },
                    "kind": {
                      "enum": [
                        "drawing"
                      ],
                      "type": "string"
                    }
                  },
                  "required": [
                    "drawingId",
                    "kind"
                  ],
                  "type": "object"
                }
              ]
            },
            "state": {
              "enum": [
                "RESPOND_TO_PROMPT"
              ],
              "type": "string"
            }
          },
          "required": [
            "players",
            "prompt",
            "state"
          ],
          "type": "object"
        },
        {
          "defaultProperties": [
          ],
          "properties": {
            "players": {
              "items": {
                "$ref": "#/definitions/ExportedPlayer1_1"
              },
              "type": "array"
            },
            "series": {
              "items": {
                "defaultProperties": [
                ],
                "properties": {
                  "entries": {
                    "items": {
                      "defaultProperties": [
                      ],
                      "properties": {
                        "playerId": {
                          "type": "string"
                        },
                        "submission": {
                          "anyOf": [
                            {
                              "defaultProperties": [
                              ],
                              "properties": {
                                "kind": {
                                  "enum": [
                                    "word"
                                  ],
                                  "type": "string"
                                },
                                "word": {
                                  "maxLength": 1024,
                                  "minLength": 1,
                                  "type": "string"
                                }
                              },
                              "required": [
                                "kind",
                                "word"
                              ],
                              "type": "object"
                            },
                            {
                              "defaultProperties": [
                              ],
                              "properties": {
                                "drawingId": {
                                  "type": "string"
                                },
                                "kind": {
                                  "enum": [
                                    "drawing"
                                  ],
                                  "type": "string"
                                }
                              },
                              "required": [
                                "drawingId",
                                "kind"
                              ],
                              "type": "object"
                            }
                          ]
                        }
                      },
                      "required": [
                        "playerId",
                        "submission"
                      ],
                      "type": "object"
                    },
                    "type": "array"
                  }
                },
                "required": [
                  "entries"
                ],
                "type": "object"
              },
              "type": "array"
            },
            "state": {
              "enum": [
                "GAME_OVER"
              ],
              "type": "string"
            }
          },
          "required": [
            "players",
            "series",
            "state"
          ],
          "type": "object"
        }
      ]
    },
    "RespondToPromptPlayerGame1_1": {
      "defaultProperties": [
      ],
      "properties": {
        "players": {
          "items": {
            "$ref": "#/definitions/ExportedPlayer1_1"
          },
          "type": "array"
        },
        "prompt": {
          "anyOf": [
            {
              "defaultProperties": [
              ],
              "properties": {
                "kind": {
                  "enum": [
                    "word"
                  ],
                  "type": "string"
                },
                "word": {
                  "maxLength": 1024,
                  "minLength": 1,
                  "type": "string"
                }
              },
              "required": [
                "kind",
                "word"
              ],
              "type": "object"
            },
            {
              "defaultProperties": [
              ],
              "properties": {
                "drawingId": {
                  "type": "string"
                },
                "kind": {
                  "enum": [
                    "drawing"
                  ],
                  "type": "string"
                }
              },
              "required": [
                "drawingId",
                "kind"
              ],
              "type": "object"
            }
          ]
        },
        "state": {
          "enum": [
            "RESPOND_TO_PROMPT"
          ],
          "type": "string"
        }
      },
      "required": [
        "players",
        "prompt",
        "state"
      ],
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'BoringPlayerGame1_1'): (value: unknown) => BoringPlayerGame1_1;
export function validate(typeName: 'RespondToPromptPlayerGame1_1'): (value: unknown) => RespondToPromptPlayerGame1_1;
export function validate(typeName: 'FinishedPlayerGame1_1'): (value: unknown) => FinishedPlayerGame1_1;
export function validate(typeName: 'ExportedPlayer1_1'): (value: unknown) => ExportedPlayer1_1;
export function validate(typeName: 'ExportedSeries1_0'): (value: unknown) => ExportedSeries1_0;
export function validate(typeName: 'ExportedSeriesEntry1_0'): (value: unknown) => ExportedSeriesEntry1_0;
export function validate(typeName: 'ActionSubmission1_0'): (value: unknown) => ActionSubmission1_0;
export function validate(typeName: 'PlayerGame1_1'): (value: unknown) => PlayerGame1_1;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: typeName}),
      );
    }

    return value as any;
  };
}