primary_id: "1.0.0"
collections:
- id: "1.0.0"
  tables:
  - id: games
    schema: [games]
    type: Game1_0
    input: true
- id: "1.0.1"
  tables:
  - id: games
    schema: [games]
    type: Game1_0
    input: true
  - id: gamesByPlayer
    schema: [player, games]
    type: PlayerGame1_0
