primary_id: "1.1.1"
collections:
- id: "1.1.0"
  tables:
  - id: games
    schema: [games]
    type: Game1_1
    input: true
  - id: shortCodeUsageCount
    schema: [shortCodes]
    type: NumberValue
    input: true
- id: "1.1.1"
  tables:
  - id: games
    schema: [games]
    type: Game1_1
    input: true
  - id: shortCodeUsageCount
    schema: [shortCodes]
    type: NumberValue
    input: true
  - id: gamesByPlayer
    schema: [players, games]
    type: Game1_1
