primary_id: "1.0.0"
collections:
- id: "1.0.0"
  actions:
  - kind: raw
  outputs:
  - id: games
    schema: [games]
    type: Game1_0
    input: true
  inputs:
  - collection_id: "1.0.0"
    table_id: games

- id: "1.0.1"
  actions:
  - kind: delta
    
  tables:
  - id: games
    schema: [games]
    type: Game1_0
    input: true
  - id: gamesByPlayer
    schema: [player, games]
    type: PlayerGame1_0
