primary_id: "1.1.1"
exports:
- id: "gamesByPlayer-1.0"
  primary_source:
    collection_id: "1.1.1"
    table_id: gamesByPlayer1_0
- id: "gamesByPlayer-1.1"
  primary_source:
    collection_id: "1.1.1"
    table_id: gamesByPlayer1_1
collections:
- id: "1.0.0"
  is_deprecated: true
  tables:
  - id: games
    schema: [games]
    type: Game1_0
- id: "1.0.1"
  is_deprecated: true
  tables:
  - id: games
    schema: [games]
    type: Game1_0
  - id: gamesByPlayer
    schema: [players, games]
    type: PlayerGame1_0
- id: "1.0.2"
  tables:
  - id: games
    schema: [games]
    type: Game1_0
  - id: gamesByPlayer
    schema: [players, games]
    type: PlayerGame1_0
- id: "1.1.0"
  is_deprecated: true
  tables:
  - id: games
    schema: [games]
    type: Game1_1
  - id: gamesByPlayer
    schema: [players, games]
    type: PlayerGame1_1
- id: "1.1.1"
  tables:
  - id: games
    schema: [games]
    type: Game1_1
  - id: gamesByPlayer1_1
    schema: [players, games]
    type: PlayerGame1_1
  - id: gamesByPlayer1_0
    schema: [players, games]
    type: PlayerGame1_0