primary_id: "1.1.1"

interfaces:
  - id: "1.0"
    exports:
      - id: "gamesByPlayer"
        schema: [players, games]
        type: PlayerGame
  - id: "1.1"
    exports:
      - id: "gamesByPlayer"
        schema: [players, games]
        type: PlayerGame

implementations:
  - id: "1.1.1"
    implements: ["1.0", "1.1"]
    private_tables:
      - id: "games"
        schema: [games]
        type: Game